// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg/Joint.proto

#include "Joint.pb.h"   //#include "msg/Joint.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace nmx {
namespace msg {
PROTOBUF_CONSTEXPR JointCmd::JointCmd(
    ::_pbi::ConstantInitialized)
  : name_(&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{})
  , pos_(0)
  , vel_(0)
  , acc_(0)
  , effort_(0){}
struct JointCmdDefaultTypeInternal {
  PROTOBUF_CONSTEXPR JointCmdDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~JointCmdDefaultTypeInternal() {}
  union {
    JointCmd _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 JointCmdDefaultTypeInternal _JointCmd_default_instance_;
PROTOBUF_CONSTEXPR JointState::JointState(
    ::_pbi::ConstantInitialized)
  : name_(&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{})
  , pos_(0)
  , vel_(0)
  , acc_(0)
  , effort_(0){}
struct JointStateDefaultTypeInternal {
  PROTOBUF_CONSTEXPR JointStateDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~JointStateDefaultTypeInternal() {}
  union {
    JointState _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 JointStateDefaultTypeInternal _JointState_default_instance_;
}  // namespace msg
}  // namespace nmx
static ::_pb::Metadata file_level_metadata_msg_2fJoint_2eproto[2];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_msg_2fJoint_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_msg_2fJoint_2eproto = nullptr;

const uint32_t TableStruct_msg_2fJoint_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::nmx::msg::JointCmd, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::nmx::msg::JointCmd, name_),
  PROTOBUF_FIELD_OFFSET(::nmx::msg::JointCmd, pos_),
  PROTOBUF_FIELD_OFFSET(::nmx::msg::JointCmd, vel_),
  PROTOBUF_FIELD_OFFSET(::nmx::msg::JointCmd, acc_),
  PROTOBUF_FIELD_OFFSET(::nmx::msg::JointCmd, effort_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::nmx::msg::JointState, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::nmx::msg::JointState, name_),
  PROTOBUF_FIELD_OFFSET(::nmx::msg::JointState, pos_),
  PROTOBUF_FIELD_OFFSET(::nmx::msg::JointState, vel_),
  PROTOBUF_FIELD_OFFSET(::nmx::msg::JointState, acc_),
  PROTOBUF_FIELD_OFFSET(::nmx::msg::JointState, effort_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::nmx::msg::JointCmd)},
  { 11, -1, -1, sizeof(::nmx::msg::JointState)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::nmx::msg::_JointCmd_default_instance_._instance,
  &::nmx::msg::_JointState_default_instance_._instance,
};

const char descriptor_table_protodef_msg_2fJoint_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\017msg/Joint.proto\022\007nmx.msg\"O\n\010JointCmd\022\014"
  "\n\004name\030\001 \001(\t\022\013\n\003pos\030\002 \001(\001\022\013\n\003vel\030\003 \001(\001\022\013"
  "\n\003acc\030\004 \001(\001\022\016\n\006effort\030\005 \001(\001\"Q\n\nJointStat"
  "e\022\014\n\004name\030\001 \001(\t\022\013\n\003pos\030\002 \001(\001\022\013\n\003vel\030\003 \001("
  "\001\022\013\n\003acc\030\004 \001(\001\022\016\n\006effort\030\005 \001(\001b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_msg_2fJoint_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_msg_2fJoint_2eproto = {
    false, false, 198, descriptor_table_protodef_msg_2fJoint_2eproto,
    "msg/Joint.proto",
    &descriptor_table_msg_2fJoint_2eproto_once, nullptr, 0, 2,
    schemas, file_default_instances, TableStruct_msg_2fJoint_2eproto::offsets,
    file_level_metadata_msg_2fJoint_2eproto, file_level_enum_descriptors_msg_2fJoint_2eproto,
    file_level_service_descriptors_msg_2fJoint_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_msg_2fJoint_2eproto_getter() {
  return &descriptor_table_msg_2fJoint_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_msg_2fJoint_2eproto(&descriptor_table_msg_2fJoint_2eproto);
namespace nmx {
namespace msg {

// ===================================================================

class JointCmd::_Internal {
 public:
};

JointCmd::JointCmd(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor();
  // @@protoc_insertion_point(arena_constructor:nmx.msg.JointCmd)
}
JointCmd::JointCmd(const JointCmd& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_name().empty()) {
    name_.Set(from._internal_name(), 
      GetArenaForAllocation());
  }
  ::memcpy(&pos_, &from.pos_,
    static_cast<size_t>(reinterpret_cast<char*>(&effort_) -
    reinterpret_cast<char*>(&pos_)) + sizeof(effort_));
  // @@protoc_insertion_point(copy_constructor:nmx.msg.JointCmd)
}

inline void JointCmd::SharedCtor() {
name_.InitDefault();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  name_.Set("", GetArenaForAllocation());
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
    reinterpret_cast<char*>(&pos_) - reinterpret_cast<char*>(this)),
    0, static_cast<size_t>(reinterpret_cast<char*>(&effort_) -
    reinterpret_cast<char*>(&pos_)) + sizeof(effort_));
}

JointCmd::~JointCmd() {
  // @@protoc_insertion_point(destructor:nmx.msg.JointCmd)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void JointCmd::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  name_.Destroy();
}

void JointCmd::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void JointCmd::Clear() {
// @@protoc_insertion_point(message_clear_start:nmx.msg.JointCmd)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  name_.ClearToEmpty();
  ::memset(&pos_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&effort_) -
      reinterpret_cast<char*>(&pos_)) + sizeof(effort_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* JointCmd::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string name = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_name();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "nmx.msg.JointCmd.name"));
        } else
          goto handle_unusual;
        continue;
      // double pos = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 17)) {
          pos_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // double vel = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 25)) {
          vel_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // double acc = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 33)) {
          acc_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // double effort = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 41)) {
          effort_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* JointCmd::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:nmx.msg.JointCmd)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string name = 1;
  if (!this->_internal_name().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_name().data(), static_cast<int>(this->_internal_name().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "nmx.msg.JointCmd.name");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_name(), target);
  }

  // double pos = 2;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_pos = this->_internal_pos();
  uint64_t raw_pos;
  memcpy(&raw_pos, &tmp_pos, sizeof(tmp_pos));
  if (raw_pos != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(2, this->_internal_pos(), target);
  }

  // double vel = 3;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_vel = this->_internal_vel();
  uint64_t raw_vel;
  memcpy(&raw_vel, &tmp_vel, sizeof(tmp_vel));
  if (raw_vel != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(3, this->_internal_vel(), target);
  }

  // double acc = 4;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_acc = this->_internal_acc();
  uint64_t raw_acc;
  memcpy(&raw_acc, &tmp_acc, sizeof(tmp_acc));
  if (raw_acc != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(4, this->_internal_acc(), target);
  }

  // double effort = 5;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_effort = this->_internal_effort();
  uint64_t raw_effort;
  memcpy(&raw_effort, &tmp_effort, sizeof(tmp_effort));
  if (raw_effort != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(5, this->_internal_effort(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:nmx.msg.JointCmd)
  return target;
}

size_t JointCmd::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:nmx.msg.JointCmd)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string name = 1;
  if (!this->_internal_name().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_name());
  }

  // double pos = 2;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_pos = this->_internal_pos();
  uint64_t raw_pos;
  memcpy(&raw_pos, &tmp_pos, sizeof(tmp_pos));
  if (raw_pos != 0) {
    total_size += 1 + 8;
  }

  // double vel = 3;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_vel = this->_internal_vel();
  uint64_t raw_vel;
  memcpy(&raw_vel, &tmp_vel, sizeof(tmp_vel));
  if (raw_vel != 0) {
    total_size += 1 + 8;
  }

  // double acc = 4;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_acc = this->_internal_acc();
  uint64_t raw_acc;
  memcpy(&raw_acc, &tmp_acc, sizeof(tmp_acc));
  if (raw_acc != 0) {
    total_size += 1 + 8;
  }

  // double effort = 5;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_effort = this->_internal_effort();
  uint64_t raw_effort;
  memcpy(&raw_effort, &tmp_effort, sizeof(tmp_effort));
  if (raw_effort != 0) {
    total_size += 1 + 8;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData JointCmd::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    JointCmd::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*JointCmd::GetClassData() const { return &_class_data_; }

void JointCmd::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<JointCmd *>(to)->MergeFrom(
      static_cast<const JointCmd &>(from));
}


void JointCmd::MergeFrom(const JointCmd& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:nmx.msg.JointCmd)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_name().empty()) {
    _internal_set_name(from._internal_name());
  }
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_pos = from._internal_pos();
  uint64_t raw_pos;
  memcpy(&raw_pos, &tmp_pos, sizeof(tmp_pos));
  if (raw_pos != 0) {
    _internal_set_pos(from._internal_pos());
  }
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_vel = from._internal_vel();
  uint64_t raw_vel;
  memcpy(&raw_vel, &tmp_vel, sizeof(tmp_vel));
  if (raw_vel != 0) {
    _internal_set_vel(from._internal_vel());
  }
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_acc = from._internal_acc();
  uint64_t raw_acc;
  memcpy(&raw_acc, &tmp_acc, sizeof(tmp_acc));
  if (raw_acc != 0) {
    _internal_set_acc(from._internal_acc());
  }
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_effort = from._internal_effort();
  uint64_t raw_effort;
  memcpy(&raw_effort, &tmp_effort, sizeof(tmp_effort));
  if (raw_effort != 0) {
    _internal_set_effort(from._internal_effort());
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void JointCmd::CopyFrom(const JointCmd& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:nmx.msg.JointCmd)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool JointCmd::IsInitialized() const {
  return true;
}

void JointCmd::InternalSwap(JointCmd* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &name_, lhs_arena,
      &other->name_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(JointCmd, effort_)
      + sizeof(JointCmd::effort_)
      - PROTOBUF_FIELD_OFFSET(JointCmd, pos_)>(
          reinterpret_cast<char*>(&pos_),
          reinterpret_cast<char*>(&other->pos_));
}

::PROTOBUF_NAMESPACE_ID::Metadata JointCmd::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_msg_2fJoint_2eproto_getter, &descriptor_table_msg_2fJoint_2eproto_once,
      file_level_metadata_msg_2fJoint_2eproto[0]);
}

// ===================================================================

class JointState::_Internal {
 public:
};

JointState::JointState(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor();
  // @@protoc_insertion_point(arena_constructor:nmx.msg.JointState)
}
JointState::JointState(const JointState& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_name().empty()) {
    name_.Set(from._internal_name(), 
      GetArenaForAllocation());
  }
  ::memcpy(&pos_, &from.pos_,
    static_cast<size_t>(reinterpret_cast<char*>(&effort_) -
    reinterpret_cast<char*>(&pos_)) + sizeof(effort_));
  // @@protoc_insertion_point(copy_constructor:nmx.msg.JointState)
}

inline void JointState::SharedCtor() {
name_.InitDefault();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  name_.Set("", GetArenaForAllocation());
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
    reinterpret_cast<char*>(&pos_) - reinterpret_cast<char*>(this)),
    0, static_cast<size_t>(reinterpret_cast<char*>(&effort_) -
    reinterpret_cast<char*>(&pos_)) + sizeof(effort_));
}

JointState::~JointState() {
  // @@protoc_insertion_point(destructor:nmx.msg.JointState)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void JointState::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  name_.Destroy();
}

void JointState::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void JointState::Clear() {
// @@protoc_insertion_point(message_clear_start:nmx.msg.JointState)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  name_.ClearToEmpty();
  ::memset(&pos_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&effort_) -
      reinterpret_cast<char*>(&pos_)) + sizeof(effort_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* JointState::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string name = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_name();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "nmx.msg.JointState.name"));
        } else
          goto handle_unusual;
        continue;
      // double pos = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 17)) {
          pos_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // double vel = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 25)) {
          vel_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // double acc = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 33)) {
          acc_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // double effort = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 41)) {
          effort_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* JointState::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:nmx.msg.JointState)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string name = 1;
  if (!this->_internal_name().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_name().data(), static_cast<int>(this->_internal_name().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "nmx.msg.JointState.name");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_name(), target);
  }

  // double pos = 2;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_pos = this->_internal_pos();
  uint64_t raw_pos;
  memcpy(&raw_pos, &tmp_pos, sizeof(tmp_pos));
  if (raw_pos != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(2, this->_internal_pos(), target);
  }

  // double vel = 3;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_vel = this->_internal_vel();
  uint64_t raw_vel;
  memcpy(&raw_vel, &tmp_vel, sizeof(tmp_vel));
  if (raw_vel != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(3, this->_internal_vel(), target);
  }

  // double acc = 4;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_acc = this->_internal_acc();
  uint64_t raw_acc;
  memcpy(&raw_acc, &tmp_acc, sizeof(tmp_acc));
  if (raw_acc != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(4, this->_internal_acc(), target);
  }

  // double effort = 5;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_effort = this->_internal_effort();
  uint64_t raw_effort;
  memcpy(&raw_effort, &tmp_effort, sizeof(tmp_effort));
  if (raw_effort != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(5, this->_internal_effort(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:nmx.msg.JointState)
  return target;
}

size_t JointState::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:nmx.msg.JointState)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string name = 1;
  if (!this->_internal_name().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_name());
  }

  // double pos = 2;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_pos = this->_internal_pos();
  uint64_t raw_pos;
  memcpy(&raw_pos, &tmp_pos, sizeof(tmp_pos));
  if (raw_pos != 0) {
    total_size += 1 + 8;
  }

  // double vel = 3;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_vel = this->_internal_vel();
  uint64_t raw_vel;
  memcpy(&raw_vel, &tmp_vel, sizeof(tmp_vel));
  if (raw_vel != 0) {
    total_size += 1 + 8;
  }

  // double acc = 4;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_acc = this->_internal_acc();
  uint64_t raw_acc;
  memcpy(&raw_acc, &tmp_acc, sizeof(tmp_acc));
  if (raw_acc != 0) {
    total_size += 1 + 8;
  }

  // double effort = 5;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_effort = this->_internal_effort();
  uint64_t raw_effort;
  memcpy(&raw_effort, &tmp_effort, sizeof(tmp_effort));
  if (raw_effort != 0) {
    total_size += 1 + 8;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData JointState::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    JointState::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*JointState::GetClassData() const { return &_class_data_; }

void JointState::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<JointState *>(to)->MergeFrom(
      static_cast<const JointState &>(from));
}


void JointState::MergeFrom(const JointState& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:nmx.msg.JointState)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_name().empty()) {
    _internal_set_name(from._internal_name());
  }
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_pos = from._internal_pos();
  uint64_t raw_pos;
  memcpy(&raw_pos, &tmp_pos, sizeof(tmp_pos));
  if (raw_pos != 0) {
    _internal_set_pos(from._internal_pos());
  }
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_vel = from._internal_vel();
  uint64_t raw_vel;
  memcpy(&raw_vel, &tmp_vel, sizeof(tmp_vel));
  if (raw_vel != 0) {
    _internal_set_vel(from._internal_vel());
  }
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_acc = from._internal_acc();
  uint64_t raw_acc;
  memcpy(&raw_acc, &tmp_acc, sizeof(tmp_acc));
  if (raw_acc != 0) {
    _internal_set_acc(from._internal_acc());
  }
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_effort = from._internal_effort();
  uint64_t raw_effort;
  memcpy(&raw_effort, &tmp_effort, sizeof(tmp_effort));
  if (raw_effort != 0) {
    _internal_set_effort(from._internal_effort());
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void JointState::CopyFrom(const JointState& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:nmx.msg.JointState)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool JointState::IsInitialized() const {
  return true;
}

void JointState::InternalSwap(JointState* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &name_, lhs_arena,
      &other->name_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(JointState, effort_)
      + sizeof(JointState::effort_)
      - PROTOBUF_FIELD_OFFSET(JointState, pos_)>(
          reinterpret_cast<char*>(&pos_),
          reinterpret_cast<char*>(&other->pos_));
}

::PROTOBUF_NAMESPACE_ID::Metadata JointState::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_msg_2fJoint_2eproto_getter, &descriptor_table_msg_2fJoint_2eproto_once,
      file_level_metadata_msg_2fJoint_2eproto[1]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace msg
}  // namespace nmx
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::nmx::msg::JointCmd*
Arena::CreateMaybeMessage< ::nmx::msg::JointCmd >(Arena* arena) {
  return Arena::CreateMessageInternal< ::nmx::msg::JointCmd >(arena);
}
template<> PROTOBUF_NOINLINE ::nmx::msg::JointState*
Arena::CreateMaybeMessage< ::nmx::msg::JointState >(Arena* arena) {
  return Arena::CreateMessageInternal< ::nmx::msg::JointState >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
